import styled from 'styled-components'
import { DetailActionLink, DetailPanel, DetailPanelBody, DetailSecondaryButton } from './WorkspaceDetailUI'

export const OrderActions = styled.div`display: flex; align-items: center; flex-wrap: wrap; gap: 10px;`
export const OrderBackLink = styled(DetailActionLink)`background: white; color: ${({ theme }) => theme.colors.textSecondary}; border: 1px solid ${({ theme }) => theme.colors.border}; &:hover { background: #f7f8fc; color: ${({ theme }) => theme.colors.text}; }`
export const OrderStack = styled(DetailPanelBody)`display: grid; gap: 18px;`
export const OrderForm = styled.form`display: grid; gap: 18px;`
export const OrderGrid = styled.div`display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; @media(max-width: 620px) { grid-template-columns: minmax(0, 1fr); }`
export const OrderField = styled.label`display: grid; gap: 8px; min-width: 0; color: ${({ theme }) => theme.colors.textSecondary}; font-size: 12px; font-weight: 650; input, select, textarea { width: 100%; min-width: 0; max-width: 100%; min-height: 42px; padding: 10px 12px; border: 1px solid ${({ theme }) => theme.colors.border}; border-radius: 8px; background: white; color: ${({ theme }) => theme.colors.text}; font: inherit; } textarea { min-height: 96px; resize: vertical; line-height: 1.7; }`
export const OrderTablePanel = styled(DetailPanel)`width: 100%; overflow: hidden;`
export const OrderTableRegion = styled.div`width: 100%; max-width: 100%; overflow-x: auto; overscroll-behavior-x: contain; scrollbar-width: thin; &:focus-visible { outline-offset: -3px; }`
export const OrderTable = styled.table`width: 100%; min-width: 850px; border-collapse: collapse; font-size: 12px; caption { position: absolute; width: 1px; height: 1px; overflow: hidden; clip-path: inset(50%); white-space: nowrap; } thead { background: #f8faf9; } th, td { padding: 16px 20px; border-bottom: 1px solid ${({ theme }) => theme.colors.border}; text-align: left; vertical-align: middle; font-variant-numeric: tabular-nums; } thead th { color: ${({ theme }) => theme.colors.textMuted}; font-size: 11px; font-weight: 600; white-space: nowrap; } tbody th { min-width: 230px; max-width: 350px; font-weight: 500; } tbody tr:last-child th, tbody tr:last-child td { border-bottom: 0; } strong { display: block; font-weight: 650; overflow-wrap: anywhere; } small { display: block; margin-top: 6px; color: ${({ theme }) => theme.colors.textMuted}; font-size: 10px; overflow-wrap: anywhere; } tbody tr:hover { background: #fcfdfc; }`
export const OrderScrollHint = styled.p`padding: 10px 22px; border-bottom: 1px solid ${({ theme }) => theme.colors.border}; color: ${({ theme }) => theme.colors.textMuted}; font-size: 10px;`
export const OrderPagination = styled.div`display: flex; justify-content: center; align-items: center; flex-wrap: wrap; gap: 18px; padding: 18px; border-top: 1px solid ${({ theme }) => theme.colors.border}; font-size: 12px; color: ${({ theme }) => theme.colors.textSecondary};`
export const OrderFacts = styled.dl`display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; margin: 0; div { min-width: 0; } dt { color: ${({ theme }) => theme.colors.textMuted}; font-size: 11px; } dd { margin: 8px 0 0; color: ${({ theme }) => theme.colors.text}; font-size: 13px; line-height: 1.8; overflow-wrap: anywhere; white-space: pre-wrap; } @media(max-width: 620px) { grid-template-columns: minmax(0, 1fr); gap: 16px; }`
export const OrderMuted = styled.p`color: ${({ theme }) => theme.colors.textMuted}; font-size: 11px; line-height: 1.8; overflow-wrap: anywhere;`
export const OrderExternalLink = styled.a`display: inline-flex; width: fit-content; color: #187d57; font-size: 12px; font-weight: 650; text-decoration: underline; text-underline-offset: 3px;`
export const OrderDangerButton = styled(DetailSecondaryButton)`color: #b33434; border-color: #efcece; &:hover { background: #fff5f5; border-color: #dea8a8; }`
export const OrderCheck = styled.label`display: flex; align-items: flex-start; gap: 9px; color: ${({ theme }) => theme.colors.textSecondary}; font-size: 12px; line-height: 1.8; input { margin-top: 4px; flex-shrink: 0; }`
